
name: 🚀 Update from Internal ZIP

on:
  push:
    paths:
      - 'trigger_update.txt'

jobs:
  update-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace project with ZIP inside repo
        run: |
          curl -L -o latest_ir_tool.zip https://raw.githubusercontent.com/Voyager9999/Voyager9999-Online-IR-spectrum-analysis-tool/main/ir_tool_auto_update.zip
          unzip -o latest_ir_tool.zip -d updated_content
          mkdir -p core data pages
          rm -rf core data pages Home.py requirements.txt || true
          cp -r updated_content/* ./
          rm -rf updated_content latest_ir_tool.zip

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "🔄 Auto-update from internal repo ZIP"
          git push
