
name: 🚀 Update from Release ZIP

on:
  push:
    paths:
      - 'trigger_update.txt'

jobs:
  update-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and extract ZIP from GitHub Release
        run: |
          curl -L -o latest_ir_tool.zip https://github.com/Voyager9999/Voyager9999-Online-IR-spectrum-analysis-tool/releases/download/V1.0/ir_tool_modular_final_updated.1.zip
          unzip -o latest_ir_tool.zip -d updated_content
          mkdir -p core data pages
          rm -rf core data pages Home.py requirements.txt || true
          cp -r updated_content/* ./
          rm -rf updated_content latest_ir_tool.zip

      - name: Commit and Push updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "🔄 Auto-update from GitHub Release ZIP"
          git push
